import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'hero.title': 'Premium Eyewear For Your Digital Lifestyle',
    'hero.subtitle': 'Order prescription glasses and designer frames online with our innovative digital fitting service',
    'hero.cta': 'Shop Collection',
    'hero.virtual': 'Try Virtually',
    'hero.tagline': 'Premium Eyewear',
    'hero.scrollDown': 'Scroll to explore',
    'featured.title': 'Featured Collections',
    'featured.viewMore': 'View More',
    'product.new': 'New',
    'about.title': 'Craftsmanship & Precision',
    'about.subtitle': 'The perfect blend of style and medical precision',
    'about.description': 'At Lens Optique, we combine decades of optical expertise with contemporary design philosophy. Each pair of glasses is crafted with meticulous attention to detail, ensuring both visual perfection and aesthetic elegance.',
    'about.quality': 'Premium Quality',
    'about.precision': 'Medical Precision',
    'about.design': 'Elegant Design',
    'about.tagline': 'About Us',
    'about.qualityDesc': 'We use only the highest quality materials for our frames and lenses.',
    'about.precisionDesc': 'Our lenses are crafted with medical-grade precision for perfect vision.',
    'about.designDesc': 'Each frame is designed with both aesthetics and comfort in mind.',
    'about.experience': 'Years Experience',
    'about.customers': 'Happy Customers',
    'about.awards': 'Design Awards',
    'about.learnMore': 'Learn More About Us',
    'footer.rights': 'All Rights Reserved',
    'digital.title': 'Digital Prescription Service',
    'digital.subtitle': 'Order your prescription glasses from the comfort of your home in 4 simple steps',
    'digital.upload.title': 'Choose Frames',
    'digital.upload.description': 'Browse our collection and select your perfect frames',
    'digital.prescription.title': 'Upload Prescription',
    'digital.prescription.description': 'Upload your digital prescription or we can contact your optometrist',
    'digital.customize.title': 'Customize Lenses',
    'digital.customize.description': 'Select lens type, coatings, and additional features',
    'digital.delivery.title': 'Home Delivery',
    'digital.delivery.description': 'Receive your custom glasses delivered to your doorstep',
    'digital.learnMore': 'Learn More',
    'digital.startNow': 'Start Your Order Now',
    'virtual.title': 'Virtual Try-On Technology',
    'virtual.description': 'See how your selected frames look on your face before making a purchase with our state-of-the-art virtual try-on technology',
    'virtual.feature1': 'Real-time face mapping using advanced AI',
    'virtual.feature2': 'Try multiple frames in seconds',
    'virtual.feature3': 'Share with friends and family for opinions',
    'virtual.cta': 'Try Frames Now',
    'virtual.new': 'New Feature',
    'virtual.demo': 'See Demo',
    'virtual.tagline': 'Virtual Experience',
    'virtual.watchDemo': 'Watch Demo Video',
    'testimonials.title': 'What Our Customers Say',
    'testimonials.subtitle': 'Hear from people who love their new Lens Optique glasses',
    'testimonials.customer': 'Satisfied Customer',
    'testimonials.quote1': 'The virtual try-on feature made choosing my frames so easy. The glasses fit perfectly and the prescription is spot on!',
    'testimonials.quote2': 'Outstanding quality and service. My new glasses arrived faster than expected and the craftsmanship is exceptional.',
    'testimonials.quote3': 'I love how easy it was to upload my prescription and customize my lenses. The blue light filter has made a huge difference for my work.',
    'store.title': 'Visit Our Flagship Store',
    'store.subtitle': 'Experience our collection in person and get expert advice from our opticians',
    'store.address': '123 Fashion Avenue, Downtown',
    'store.city': 'New York, NY 10001',
    'store.hours': 'Opening Hours:',
    'store.weekdays': 'Monday - Friday: 9AM - 8PM',
    'store.weekend': 'Saturday - Sunday: 10AM - 6PM',
    'store.cta': 'Get Directions',
    'store.appointment': 'Book Appointment',
    'store.services': 'In-Store Services:',
    'store.service1': 'Professional Eye Exams',
    'store.service2': 'Frame Styling Consultation',
    'store.service3': 'Adjustments & Repairs',
    'store.service4': 'Lens Prescription Check',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.products': 'Produits',
    'nav.about': 'À Propos',
    'nav.contact': 'Contact',
    'hero.title': 'Lunettes Premium Pour Votre Mode de Vie Numérique',
    'hero.subtitle': 'Commandez des lunettes de vue et des montures de créateur en ligne avec notre service d\'ajustement numérique innovant',
    'hero.cta': 'Voir la Collection',
    'hero.virtual': 'Essayer Virtuellement',
    'hero.tagline': 'Lunettes Premium',
    'hero.scrollDown': 'Défiler pour explorer',
    'featured.title': 'Collections en Vedette',
    'featured.viewMore': 'Voir Plus',
    'product.new': 'Nouveau',
    'about.title': 'Artisanat & Précision',
    'about.subtitle': 'Le mélange parfait de style et de précision médicale',
    'about.description': 'Chez Lens Optique, nous combinons des décennies d\'expertise optique avec une philosophie de design contemporaine. Chaque paire de lunettes est fabriquée avec une attention méticuleuse aux détails, assurant à la fois une perfection visuelle et une élégance esthétique.',
    'about.quality': 'Qualité Premium',
    'about.precision': 'Précision Médicale',
    'about.design': 'Design Élégant',
    'about.tagline': 'À Propos de Nous',
    'about.qualityDesc': 'Nous utilisons uniquement des matériaux de la plus haute qualité pour nos montures et verres.',
    'about.precisionDesc': 'Nos verres sont fabriqués avec une précision de qualité médicale pour une vision parfaite.',
    'about.designDesc': 'Chaque monture est conçue en pensant à l\'esthétique et au confort.',
    'about.experience': 'Années d\'Expérience',
    'about.customers': 'Clients Satisfaits',
    'about.awards': 'Prix de Design',
    'about.learnMore': 'En Savoir Plus Sur Nous',
    'digital.title': 'Service de Prescription Numérique',
    'digital.subtitle': 'Commandez vos lunettes de prescription depuis le confort de votre domicile en 4 étapes simples',
    'digital.upload.title': 'Choisir des Montures',
    'digital.upload.description': 'Parcourez notre collection et sélectionnez vos montures parfaites',
    'digital.prescription.title': 'Télécharger l\'Ordonnance',
    'digital.prescription.description': 'Téléchargez votre ordonnance numérique ou nous pouvons contacter votre opticien',
    'digital.customize.title': 'Personnaliser les Verres',
    'digital.customize.description': 'Sélectionnez le type de verre, les revêtements et les fonctionnalités supplémentaires',
    'digital.delivery.title': 'Livraison à Domicile',
    'digital.delivery.description': 'Recevez vos lunettes personnalisées livrées à votre porte',
    'digital.learnMore': 'En Savoir Plus',
    'digital.startNow': 'Commencer Votre Commande',
    'virtual.title': 'Technologie d\'Essayage Virtuel',
    'virtual.description': 'Voyez comment les montures sélectionnées s\'adaptent à votre visage avant d\'acheter grâce à notre technologie d\'essayage virtuel de pointe',
    'virtual.feature1': 'Cartographie du visage en temps réel utilisant l\'IA avancée',
    'virtual.feature2': 'Essayez plusieurs montures en quelques secondes',
    'virtual.feature3': 'Partagez avec vos amis et votre famille pour obtenir des avis',
    'virtual.cta': 'Essayer des Montures Maintenant',
    'virtual.new': 'Nouvelle Fonctionnalité',
    'virtual.demo': 'Voir la Démo',
    'virtual.tagline': 'Expérience Virtuelle',
    'virtual.watchDemo': 'Regarder la Vidéo de Démo',
    'testimonials.title': 'Ce Que Disent Nos Clients',
    'testimonials.subtitle': 'Écoutez les personnes qui adorent leurs nouvelles lunettes Lens Optique',
    'testimonials.customer': 'Client Satisfait',
    'testimonials.quote1': 'La fonction d\'essayage virtuel a rendu le choix de mes montures si facile. Les lunettes s\'adaptent parfaitement et la prescription est impeccable!',
    'testimonials.quote2': 'Qualité et service exceptionnels. Mes nouvelles lunettes sont arrivées plus rapidement que prévu et le savoir-faire est exceptionnel.',
    'testimonials.quote3': 'I love how easy it was to upload my prescription and customize my lenses. The blue light filter has made a huge difference for my work.',
    'store.title': 'Visitez Notre Boutique Phare',
    'store.subtitle': 'Découvrez notre collection en personne et obtenez des conseils d\'experts de nos opticiens',
    'store.address': '123 Avenue de la Mode, Centre-ville',
    'store.city': 'Paris, 75001',
    'store.hours': 'Heures d\'ouverture:',
    'store.weekdays': 'Lundi - Vendredi: 9h - 20h',
    'store.weekend': 'Samedi - Dimanche: 10h - 18h',
    'store.cta': 'Obtenir l\'itinéraire',
    'store.appointment': 'Prendre Rendez-vous',
    'store.services': 'Services en Magasin:',
    'store.service1': 'Examens Professionnels de la Vue',
    'store.service2': 'Consultation de Style de Monture',
    'store.service3': 'Ajustements & Réparations',
    'store.service4': 'Vérification de Prescription de Verres',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.products': 'المنتجات',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    'hero.title': 'نظارات فاخرة لأسلوب حياتك الرقمي',
    'hero.subtitle': 'اطلب النظارات الطبية وإطارات المصممين عبر الإنترنت من خلال خدمة التركيب الرقمية المبتكرة',
    'hero.cta': 'تسوق المجموعة',
    'hero.virtual': 'جرّب افتراضيًا',
    'hero.tagline': 'نظارات فاخرة',
    'hero.scrollDown': 'مرر للاستكشاف',
    'featured.title': 'المجموعات المميزة',
    'featured.viewMore': 'عرض المزيد',
    'product.new': 'جديد',
    'about.title': 'الحرفية والدقة',
    'about.subtitle': 'المزيج المثالي من الأناقة والدقة الطبية',
    'about.description': 'في لينز أوبتيك، نجمع بين عقود من الخبرة البصرية وفلسفة التصميم المعاصرة. يتم تصنيع كل زوج من النظارات مع الاهتمام الدقيق بالتفاصيل، مما يضمن الكمال البصري والأناقة الجمالية.',
    'about.quality': 'جودة ممتازة',
    'about.precision': 'دقة طبية',
    'about.design': 'تصميم أنيق',
    'about.tagline': 'من نحن',
    'about.qualityDesc': 'نستخدم فقط مواد ذات جودة عالية لإطاراتنا وعدساتنا.',
    'about.precisionDesc': 'تصنع عدساتنا بدقة طبية للرؤية المثالية.',
    'about.designDesc': 'كل إطار مصمم مع مراعاة الجمالية والراحة.',
    'about.experience': 'سنوات الخبرة',
    'about.customers': 'زبائن سعداء',
    'about.awards': 'جوائز التصميم',
    'about.learnMore': 'تعرف علينا أكثر',
    'digital.title': 'خدمة الوصفات الطبية الرقمية',
    'digital.subtitle': 'اطلب نظاراتك الطبية من راحة منزلك في 4 خطوات بسيطة',
    'digital.upload.title': 'اختيار الإطارات',
    'digital.upload.description': 'تصفح مجموعتنا واختر إطاراتك المثالية',
    'digital.prescription.title': 'تحميل الوصفة الطبية',
    'digital.prescription.description': 'قم بتحميل وصفتك الطبية الرقمية أو يمكننا الاتصال بطبيب العيون الخاص بك',
    'digital.customize.title': 'تخصيص العدسات',
    'digital.customize.description': 'اختر نوع العدسة والطلاءات والميزات الإضافية',
    'digital.delivery.title': 'التوصيل للمنزل',
    'digital.delivery.description': 'استلم نظاراتك المخصصة موصلة إلى باب منزلك',
    'digital.learnMore': 'تعرف على المزيد',
    'digital.startNow': 'ابدأ طلبك الآن',
    'virtual.title': 'تقنية التجربة الافتراضية',
    'virtual.description': 'شاهد كيف تبدو الإطارات المختارة على وجهك قبل الشراء باستخدام تقنية التجربة الافتراضية المتطورة',
    'virtual.feature1': 'رسم خرائط الوجه في الوقت الفعلي باستخدام الذكاء الاصطناعي المتقدم',
    'virtual.feature2': 'جرب إطارات متعددة في ثوانٍ',
    'virtual.feature3': 'شارك مع الأصدقاء والعائلة للحصول على الآراء',
    'virtual.cta': 'جرب الإطارات الآن',
    'virtual.new': 'ميزة جديدة',
    'virtual.demo': 'شاهد العرض التوضيحي',
    'virtual.tagline': 'تجربة افتراضية',
    'virtual.watchDemo': 'مشاهدة فيديو العرض التوضيحي',
    'testimonials.title': 'ماذا يقول عملاؤنا',
    'testimonials.subtitle': 'استمع إلى الأشخاص الذين يحبون نظاراتهم الجديدة من لينز أوبتيك',
    'testimonials.customer': 'زبون راضي',
    'testimonials.quote1': 'جعلت ميزة التجربة الافتراضية اختيار إطاراتي سهلاً للغاية. النظارات مناسبة تمامًا والوصفة الطبية مثالية!',
    'testimonials.quote2': 'جودة وخدمة استثنائية. وصلت نظاراتي الجديدة بشكل أسرع من المتوقع والحرفية استثنائية.',
    'testimonials.quote3': 'أحب مدى سهولة تحميل وصفتي الطبية وتخصيص عدساتي. لقد أحدث مرشح الضوء الأزرق فرقًا كبيرًا في عملي.',
    'store.title': 'زيارة متجرنا الرئيسي',
    'store.subtitle': 'استكشف مجموعتنا شخصيًا واحصل على نصائح الخبراء من البصريين لدينا',
    'store.address': '١٢٣ شارع الموضة، وسط المدينة',
    'store.city': 'دبي، الإمارات العربية المتحدة',
    'store.hours': 'ساعات العمل:',
    'store.weekdays': 'الإثنين - الجمعة: ٩ صباحًا - ٨ مساءً',
    'store.weekend': 'السبت - الأحد: ١٠ صباحًا - ٦ مساءً',
    'store.cta': 'الحصول على الاتجاهات',
    'store.appointment': 'حجز موعد',
    'store.services': 'خدمات المتجر:',
    'store.service1': 'فحوصات العين المهنية',
    'store.service2': 'استشارة تصميم الإطار',
    'store.service3': 'تعديلات وإصلاحات',
    'store.service4': 'فحص وصفة العدسات',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
